#ifndef __GAME_DATA_H__
#define __GAME_DATA_H__

/* This is (or will be) an autogenerated file. Do not modify directly! */

#include "game.h"

#define INITIAL_ROOM lounge

// Define rooms
static Room lounge = {
    "lounge",
    NULL,
    "This is quite a plain lounge with an old beige carpet and peeling wallpaper.",
    { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    NULL,
};

static Room kitchen = {
    "kitchen",
    NULL,
    "Just an ordinary kitchen.",
    { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    NULL,
};


static void __fastcall__ connect_rooms(void) {
    lounge.exits[S] = &kitchen;
    kitchen.exits[N] = &lounge;
}

static void __fastcall__ initialize_world(void) {
    connect_rooms();
}

void start(void) {
    initialize_world();
    move_to(&INITIAL_ROOM);
}

#endif
